apiVersion: v1
kind: Service
metadata:
  labels:
    service: person-service
  name: person-service
spec:
  ports:
    - name: "5000"
      port: 5000
      targetPort: 5000
      nodePort: 30011
  selector:
    service: person-service
  type: NodePort