---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: connection-service
  name: connection-service
spec:
  replicas: 1
  selector:
    matchLabels:
      service: connection-service
  template:
    metadata:
      labels:
        service: connection-service
    spec:
      containers:
        - image: codecritics/udaconnect-connection_service:latest
          name: connection-service
          imagePullPolicy: Always
          env:
            - name: DB_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: db-env
                  key: DB_USERNAME
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: DB_PASSWORD
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: db-env
                  key: DB_NAME
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: db-env
                  key: DB_HOST
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: db-env
                  key: DB_PORT
      restartPolicy: Always