apiVersion: v1
kind: Service
metadata:
  labels:
    service: connection-service
  name: connection-service
spec:
  ports:
    - name: "5000"
      port: 5000
      targetPort: 5000
      nodePort: 30016
  selector:
    service: connection-service
  type: NodePort